FROM ubuntu:16.04

MAINTAINER fuhongbo@live.cn

ENV http_proxy $HTTP_PROXY
ENV https_proxy $HTTP_PROXY

RUN mv /etc/apt/sources.list /etc/apt/sources.list.bak && \
    echo "deb-src http://archive.ubuntu.com/ubuntu xenial main restricted" >/etc/apt/sources.list && \
    echo "deb http://mirrors.aliyun.com/ubuntu/ xenial main restricted" >>/etc/apt/sources.list && \
    echo "deb-src http://mirrors.aliyun.com/ubuntu/ xenial main restricted multiverse universe" >>/etc/apt/sources.list && \
    echo "deb http://mirrors.aliyun.com/ubuntu/ xenial-updates main restricted" >>/etc/apt/sources.list && \
    echo "deb-src http://mirrors.aliyun.com/ubuntu/ xenial-updates main restricted multiverse universe" >>/etc/apt/sources.list && \
    echo "deb http://mirrors.aliyun.com/ubuntu/ xenial universe" >>/etc/apt/sources.list && \
    echo "deb http://mirrors.aliyun.com/ubuntu/ xenial-updates universe" >>/etc/apt/sources.list && \
    echo "deb http://mirrors.aliyun.com/ubuntu/ xenial multiverse" >>/etc/apt/sources.list && \
    echo "deb http://mirrors.aliyun.com/ubuntu/ xenial-updates multiverse" >>/etc/apt/sources.list && \
    echo "deb http://mirrors.aliyun.com/ubuntu/ xenial-backports main restricted universe multiverse" >>/etc/apt/sources.list && \
    echo "deb-src http://mirrors.aliyun.com/ubuntu/ xenial-backports main restricted universe multiverse" >>/etc/apt/sources.list && \
    echo "deb http://archive.canonical.com/ubuntu xenial partner" >>/etc/apt/sources.list && \
    echo "deb-src http://archive.canonical.com/ubuntu xenial partner" >>/etc/apt/sources.list && \
    echo "deb http://mirrors.aliyun.com/ubuntu/ xenial-security main restricted" >>/etc/apt/sources.list && \
    echo "deb-src http://mirrors.aliyun.com/ubuntu/ xenial-security main restricted multiverse universe" >>/etc/apt/sources.list && \
    echo "deb http://mirrors.aliyun.com/ubuntu/ xenial-security universe" >>/etc/apt/sources.list && \
    echo "deb http://mirrors.aliyun.com/ubuntu/ xenial-security multiverse" >>/etc/apt/sources.list

ADD ./l_openvino_toolkit_p_2019.1.144 /app/l_openvino_toolkit_p_2019.1.144

WORKDIR /app

RUN apt-get update &&\
    apt-get autoremove -y &&\
    apt-get install -y --no-install-recommends \
      cpio \
      lsb-release \
      python3.5 \
      python3-pip \
      sudo \
      libusb-1.0-0 libboost-program-options1.58.0 \
      libboost-thread1.58.0 libboost-filesystem1.58.0 \
      libssl1.0.0 libudev1 libjson-c2 wget \
      && \
      rm -rf /var/lib/apt/lists/* && \
      cd l_openvino_toolkit* && \
        ./install_openvino_dependencies.sh &&\
        sed -i 's/decline/accept/g' silent.cfg && \
        ./install.sh --silent silent.cfg && \
        rm -r /app/l_openvino_toolkit*  && \
        echo "source /opt/intel/openvino/bin/setupvars.sh" >> ~/.bashrc

RUN python3.5 -m pip install setuptools -U pip && \
        pip3 install pyyaml requests opencv-python && \
        rm -rf /var/lib/apt/lists/* && \
        rm -rf /opt/intel/openvino/openvx/include && \
        rm -rf /opt/intel/openvino/openvx/samples && \
        rm -rf /opt/intel/openvino/deployment_tools/demo && \
        rm -rf /opt/intel/openvino/deployment_tools/intel_models && \
        rm -rf /opt/intel/openvino/deployment_tools/model_optimizer && \
        rm -rf /opt/intel/openvino/deployment_tools/tools && \
        rm -rf /opt/intel/openvino/deployment_tools/inference_engine/samples && \
        rm -rf /opt/intel/openvino/deployment_tools/inference_engine/external && \
        rm -rf /opt/intel/openvino/deployment_tools/inference_engine/include && \
        rm -rf /opt/intel/openvino/deployment_tools/inference_engine/share && \
        rm -rf /opt/intel/openvino/deployment_tools/inference_engine/src && \
        rm -rf /opt/intel/openvino/install_dependencies && \
        rm -rf /opt/intel/openvino/licensing && \
        rm -rf /opt/intel/openvino/opencv/cmake && \
        rm -rf /opt/intel/openvino/opencv/etc && \
        rm -rf /opt/intel/openvino/opencv/include && \
        rm -rf /opt/intel/openvino/opencv/samples && \
        rm -rf /opt/intel/openvino/opencv/setupvars.sh && \
        rm -rf /opt/intel/openvino/opencv/third-party-programs.txt && \
        rm -rf /opt/intel/openvino/opencv/version.txt && \
        rm -rf /opt/intel/openvino/openvino_toolkit_uninstaller && \
        rm -rf /opt/intel/openvino/openvx/include && \
        rm -rf /opt/intel/openvino/openvx/samples && \
        rm -rf /opt/intel/openvino/openvx/python2.7 && \
        rm -rf /opt/intel/openvino/python/python3.4 && \
        rm -rf /opt/intel/openvino/python/python3.6 && \
        rm -rf /opt/intel/openvino/python/python3.7 && \
        apt-get clean && \
        apt-get autoremove

